In [1]:
import numpy as np

In [3]:
tDarray=np.arange(20).reshape(4,5)
tDarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
tDarray[3,2]

17

In [5]:
tDarray[1,3]

8

In [6]:
tDarray[2,1]

11

In [7]:
tDarray[1,]

array([5, 6, 7, 8, 9])

In [8]:
tDarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
tDarray[1:3,1:2]

array([[ 6],
       [11]])

In [10]:
tDarray[1:3,3:5]

array([[ 8,  9],
       [13, 14]])

In [11]:
tDarray[:,4]

array([ 4,  9, 14, 19])

In [12]:
tDarray[3:4,0:5]

array([[15, 16, 17, 18, 19]])

In [13]:
tDarray[3,]

array([15, 16, 17, 18, 19])

In [14]:
alist = [11,22,33,44,55,66,77,88,99]

In [15]:
alist[-3:-6]

[]

In [23]:
a=np.arange(88).reshape(8,11)

In [24]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]])