In [12]:
import numpy as np

In [13]:
a=np.ones((4,5))

In [14]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
a*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [16]:
full = np.full((4,5),5)

In [17]:
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [18]:
b=np.array(3,3)

TypeError: data type not understood

In [19]:
b=np.arange(9).reshape(3,3)

In [20]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
b[:2,1:]

array([[1, 2],
       [4, 5]])

In [22]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
b[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [24]:
data=np.random.randn(7,4)

In [30]:
names=np.array(["Bob","Joe","Will","kkk","jkhk","hjh","jhikj"])

In [31]:
data[names=='Bob',2:]

array([[ 1.40567413, -0.14150196]])

In [32]:
data

array([[ 0.97744042,  1.47722877,  1.40567413, -0.14150196],
       [-0.64305191, -0.02947937, -0.04380099,  0.95079147],
       [-0.12588411,  0.91068391, -1.65024093,  0.9414018 ],
       [ 1.35325698,  0.146918  ,  2.81880231, -0.45711527],
       [-0.39040332, -0.38533746, -0.25103742, -0.08291359],
       [-0.6606035 ,  0.018264  ,  0.43402972, -0.9903897 ],
       [-1.63401246, -0.0317693 , -0.89382933, -0.40562556]])

In [33]:
names=="Bob"

array([ True, False, False, False, False, False, False])

In [34]:
data[names=="Bob"]

array([[ 0.97744042,  1.47722877,  1.40567413, -0.14150196]])

In [43]:
mat1=np.arange(12).reshape(3,4)
mat2=np.array([[4,5,6,7],[3,4,5,6,],[9,7,6,5]])

In [46]:
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
mat2

array([[4, 5, 6, 7],
       [3, 4, 5, 6],
       [9, 7, 6, 5]])

In [45]:
mat1 * mat2

array([[ 0,  5, 12, 21],
       [12, 20, 30, 42],
       [72, 63, 60, 55]])

In [47]:
mat3=mat2=np.array([[4,5,6,7],[3,4,5,6,],[9,7,6,5],[3,2,6,8]])

In [48]:
mat1@mat3

array([[ 30,  24,  35,  40],
       [106,  96, 127, 144],
       [182, 168, 219, 248]])

In [51]:
#mat1.dot(mat3)
np.dot(mat1,mat3)

array([[ 30,  24,  35,  40],
       [106,  96, 127, 144],
       [182, 168, 219, 248]])

In [52]:
mat3@mat1

ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [53]:
from numpy.linalg import inv, qr

In [54]:
x=np.random.randn(5, 5)

In [55]:
mat = X.T.dot(X)

NameError: name 'X' is not defined